### ISSUE TITLE
Not able to build linux shared library

### ISSUE THREAD

**Issue by JorisKoster** [jxcore/jxcore#830]
After fix #817 I can no longer build the jxcore shared library on linux. It complains about duplicate symbols during link step. Reverting #817 solves the problem for me. Not sure what the proper solution would be. Something like 

`      ['node_shared_library==1',
      {
        'defines!': ['HAVE_DTRACE'],
        'defines': ['JXCORE_EMBEDDED'],
        'conditions': [
          ['OS=="mac"', {
            'type': 'shared_library'
          }, {
            'type': 'loadable_module'
          }]
        ]
      }],
`
i.e. specialize for mac instead of windows? Works for me, but I have no Mac to test it on.

**Comment by obastemur** [comment]
OS in "mac ios"

I would appreciate if you can send a PR with your and the suggestion above

**Comment by JorisKoster** [comment]
k will do
